CREATE TABLE "accounts" (
	"ACCOUNT_ID"	INTEGER,
	"FIRST_NAME"	TEXT NOT NULL,
	"LAST_NAME"	TEXT NOT NULL,
	"USER_NAME" TEXT NOT NULL UNIQUE,
	"BIRTHDATE"	TEXT NOT NULL,
	"PHONE_NUMBER"	TEXT NOT NULL,
	"EMAIL"	TEXT NOT NULL UNIQUE,
	"PASSWORD" TEXT NOT NULL,
	"ADDRESS_ID"	INTEGER NOT NULL,
	"ROLE_ID" INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("ADDRESS_ID") REFERENCES "addresses"("ID"),
	FOREIGN KEY("ROLE_ID") REFERENCES "roles"("ROLE_ID"),
);
CREATE TABLE "roles" (
	"ROLE_ID"	INTEGER NOT NULL UNIQUE,
	"ROLE_TYPE" TEXT NOT NULL CHECK("ROLE_TYPE" IN ('admin', 'user')),
	PRIMARY KEY("ROLE_ID")
);
CREATE TABLE "user_signup_status" (
	"USER_ID"	INTEGER NOT NULL,
	"STATUS" TEXT NOT NULL CHECK("STATUS" IN ('pending', 'approved', 'rejected')),
	PRIMARY KEY("USER_ID"),
	FOREIGN KEY("USER_ID") REFERENCES "users"("USER_ID")
);
CREATE TABLE "addresses" (
	"ID"	INTEGER,
	"STREET"	TEXT NOT NULL,
	"CITY"	TEXT NOT NULL,
	"PROVINCE"	TEXT NOT NULL,
	"POSTAL_CODE"	TEXT NOT NULL,
	UNIQUE("STREET","CITY","PROVINCE","POSTAL_CODE"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE "equipment_details" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"CATEGORY_ID" INTEGER NOT NULL,
	"AVAILABILITY_ID" INTEGER NOT NULL,
	"NAME"	TEXT NOT NULL,
	"DESCRIPTION" TEXT NOT NULL,
	"IS_ONSITE_ONLY" INTEGER NOT NULL CHECK("IS_ONSITE_ONLY" IN (0, 1)),
	"WARRANTY_YEARS" INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("CATEGORY_ID") REFERENCES "equipment_category"("CATEGORY_ID")
);
CREATE TABLE "equipment_category" (
	"CATEGORY_ID"	INTEGER NOT NULL UNIQUE,
	"CATEGORY_NAME"	TEXT NOT NULL,
	PRIMARY KEY("CATEGORY_ID" AUTOINCREMENT)
);
CREATE TABLE "equipment_inventory" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"LENT" INTEGER NOT NULL,
	"AVAILABLE" INTEGER NOT NULL,
	PRIMARY KEY("ID"),
	FOREIGN KEY("ID") REFERENCES "equipment_details"("ID"),
);
CREATE TABLE "equipment_reservations" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"EQUIPMENT_ID" INTEGER NOT NULL,
	"RESERVATION_ID" INTEGER,
	"BORROW_DATE" TEXT NOT NULL,
	"RETURN_DATE" TEXT NOT NULL,
	"PURPOSE"	TEXT NOT NULL,
	"RESERVATION_TYPE" TEXT NOT NULL CHECK(RESERVATION_TYPE IN ('onsite', 'borrow')),
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("RESERVATION_ID") REFERENCES "reservations"("RESERVATION_ID"),
	FOREIGN KEY("EQUIPMENT_ID") REFERENCES "equipment_details"("ID")
);
CREATE TABLE "reservations" (
	"RESERVATION_ID"	INTEGER NOT NULL,
	"USER_ID" INTEGER NOT NULL,
	"CREATED_DATE" TEXT NOT NULL,
	"CREATED_TIME"	TEXT NOT NULL,
	"STATUS_ID"	INTEGER NOT NULL,
	PRIMARY KEY("RESERVATION_ID" AUTOINCREMENT),
	FOREIGN KEY("USER_ID") REFERENCES "users"("USER_ID")
);
CREATE TABLE "reservation_status" (
	"RESERVATION_ID"	INTEGER NOT NULL,
	"STATUS" TEXT NOT NULL CHECK(STATUS IN ('pending', 'approved', 'rejected')),
	PRIMARY KEY("RESERVATION_ID"),
	FOREIGN KEY("RESERVATION_ID") REFERENCES "reservations"("RESERVATION_ID")
);