# Generated by Django 4.2.11 on 2024-04-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_reservationstatus_reservation_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accounts',
            table='Accounts',
        ),
        migrations.AlterModelTable(
            name='addresses',
            table='Addresses',
        ),
        migrations.AlterModelTable(
            name='equipmentcategory',
            table='EquipmentCategory',
        ),
        migrations.AlterModelTable(
            name='equipmentdetails',
            table='EquipmentDetails',
        ),
        migrations.AlterModelTable(
            name='equipmentinventory',
            table='EquipmentInventory',
        ),
        migrations.AlterModelTable(
            name='equipmentreservations',
            table='EquipmentReservations',
        ),
        migrations.AlterModelTable(
            name='reservations',
            table='Reservations',
        ),
        migrations.AlterModelTable(
            name='reservationstatus',
            table='ReservationStatus',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='Roles',
        ),
        migrations.AlterModelTable(
            name='usersignupstatus',
            table='UserSignupStatus',
        ),
    ]
