# Generated by Django 4.2.11 on 2024-04-24 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_accounts_table_alter_addresses_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='CREATED_DATE',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='CREATED_TIME',
        ),
        migrations.AddField(
            model_name='reservations',
            name='CREATED_DATETIME',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 24, 22, 39, 20, 549715, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservations',
            name='UPDATED_DATETIME',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentreservations',
            name='BORROW_DATE',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='equipmentreservations',
            name='RETURN_DATE',
            field=models.DateField(),
        ),
    ]
