# Generated by Django 4.2.11 on 2024-04-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_reservations_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentdetails',
            name='AVAILABILITY_ID',
        ),
        migrations.AlterField(
            model_name='equipmentinventory',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.equipmentdetails'),
        ),
    ]
